/* Regenerates public/sitemap.xml + public/robots.txt from the app's own route
   data, so the sitemap cannot drift from the cities and products actually
   shipped. Run via `npm run sitemap` (also runs automatically on `npm run build`).

   Blog posts are database-driven and are intentionally not listed here — add a
   dynamic /sitemap-blog.xml from the backend if those need indexing. */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { SITE_ORIGIN } from '../src/config/site.js';
import { CITIES } from '../src/data/cities.js';
import { PRODUCT_CARDS } from '../src/data/products.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = resolve(__dirname, '../public');
const today = new Date().toISOString().slice(0, 10);

const urls = [
  { loc: '/', changefreq: 'monthly', priority: '1.0' },
  { loc: '/about', changefreq: 'yearly', priority: '0.6' },
  { loc: '/blog', changefreq: 'weekly', priority: '0.8' },
  { loc: '/products', changefreq: 'monthly', priority: '0.9' },
  { loc: '/gallery', changefreq: 'monthly', priority: '0.7' },
  { loc: '/locations', changefreq: 'monthly', priority: '0.9' },
  ...CITIES.map((c) => ({
    loc: `/locations/${c.slug}`,
    changefreq: 'monthly',
    priority: c.isHeadOffice ? '0.9' : '0.8',
  })),
  ...PRODUCT_CARDS.map((p) => ({
    loc: `/product/${p.id}`,
    changefreq: 'monthly',
    priority: '0.7',
  })),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    ({ loc, changefreq, priority }) => `  <url>
    <loc>${SITE_ORIGIN}${loc === '/' ? '/' : loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`,
  )
  .join('\n')}
</urlset>
`;

const robots = `# Generated by scripts/generate-sitemap.mjs — do not edit by hand.
User-agent: *
Allow: /
Disallow: /admin
Disallow: /admin/

Sitemap: ${SITE_ORIGIN}/sitemap.xml
`;

mkdirSync(publicDir, { recursive: true });
writeFileSync(resolve(publicDir, 'sitemap.xml'), xml, 'utf8');
writeFileSync(resolve(publicDir, 'robots.txt'), robots, 'utf8');

console.log(`sitemap.xml: ${urls.length} URLs (${CITIES.length} city pages)`);
console.log('robots.txt written');
